# Generated by Django 4.2.11 on 2024-04-26 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contactos', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Task',
            new_name='Contacto',
        ),
    ]
