# Generated by Django 4.2.11 on 2024-04-26 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contactos', '0002_rename_task_contacto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contacto',
            old_name='title',
            new_name='mensaje_contacto',
        ),
        migrations.RemoveField(
            model_name='contacto',
            name='completed',
        ),
    ]
