# Generated by Django 4.2.11 on 2024-04-30 19:38

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('contactos', '0003_rename_title_contacto_mensaje_contacto_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estado_contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_contacto', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_contacto', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='contacto',
            name='mensaje_contacto',
        ),
        migrations.AddField(
            model_name='contacto',
            name='correo',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contacto',
            name='mensaje',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contacto',
            name='nombre',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contacto',
            name='estado_contacto',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='contactos.estado_contacto'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contacto',
            name='tipo_contacto',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='contactos.tipo_contacto'),
            preserve_default=False,
        ),
    ]
