# Generated by Django 4.2.11 on 2024-04-30 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contactos', '0004_estado_contacto_tipo_contacto_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contacto',
            old_name='mensaje',
            new_name='mensaje_contacto',
        ),
    ]
