# Generated by Django 4.2.11 on 2024-04-30 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contactos', '0005_rename_mensaje_contacto_mensaje_contacto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contacto',
            old_name='estado_contacto',
            new_name='estado_contacto_id',
        ),
        migrations.RenameField(
            model_name='contacto',
            old_name='tipo_contacto',
            new_name='tipo_contacto_id',
        ),
    ]
