# Generated by Django 4.2.11 on 2024-05-04 01:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contactos', '0006_alter_contacto_correo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacto',
            name='estado_contacto',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='contactos.estado_contacto'),
        ),
    ]
