# Generated by Django 4.2.11 on 2024-04-30 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactos', '0006_rename_estado_contacto_contacto_estado_contacto_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contacto',
            old_name='estado_contacto_id',
            new_name='estado_contacto',
        ),
        migrations.RenameField(
            model_name='contacto',
            old_name='tipo_contacto_id',
            new_name='tipo_contacto',
        ),
        migrations.RemoveField(
            model_name='estado_contacto',
            name='id',
        ),
        migrations.RemoveField(
            model_name='tipo_contacto',
            name='id',
        ),
        migrations.AddField(
            model_name='estado_contacto',
            name='estado_contacto_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tipo_contacto',
            name='tipo_contacto_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
