# Generated by Django 4.2.11 on 2024-06-15 05:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactos', '0007_alter_contacto_estado_contacto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacto',
            name='correo',
            field=models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator(code='invalid_correo', message='Introduzca una dirección de correo electrónico válida')]),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='mensaje_contacto',
            field=models.CharField(max_length=300, validators=[django.core.validators.MinLengthValidator(10), django.core.validators.RegexValidator(code='invalid_mensaje_contacto', message='El mensaje solo puede contener letras y puntos. Además, no pueden ser solo puntos.', regex='^(?!.*[^a-zA-Z. ])[a-zA-Z]+(?:[a-zA-Z. ]*[a-zA-Z]+)*$')]),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='nombre',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(code='invalid_nombre', message='El nombre solo puede contener letras', regex='^[a-zA-Z]+$')]),
        ),
        migrations.AlterField(
            model_name='tipo_contacto',
            name='tipo_contacto',
            field=models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(3), django.core.validators.RegexValidator(message='El tipo de contacto solo puede contener letras y debe ser mayor a 3 letras', regex='^[a-zA-Z]+$')]),
        ),
    ]
