# Generated by Django 4.2.11 on 2024-04-30 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactos', '0007_rename_estado_contacto_id_contacto_estado_contacto_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estado_contacto',
            name='estado_contacto_id',
        ),
        migrations.RemoveField(
            model_name='tipo_contacto',
            name='tipo_contacto_id',
        ),
        migrations.AddField(
            model_name='estado_contacto',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tipo_contacto',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
