# Generated by Django 4.2.11 on 2024-06-15 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactos', '0008_alter_contacto_correo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacto',
            name='respuesta',
            field=models.TextField(blank=True, null=True),
        ),
    ]
