# Generated by Django 4.2.11 on 2024-04-30 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactos', '0008_remove_estado_contacto_estado_contacto_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estado_contacto',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tipo_contacto',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
