# Generated by Django 4.2.11 on 2024-04-30 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contactos', '0009_alter_estado_contacto_id_alter_tipo_contacto_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contacto',
            old_name='estado_contacto',
            new_name='id_estado',
        ),
        migrations.RenameField(
            model_name='contacto',
            old_name='tipo_contacto',
            new_name='id_tipo',
        ),
    ]
