# Generated by Django 4.2.11 on 2024-07-05 22:44

import contactos.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactos', '0010_alter_contacto_mensaje_contacto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacto',
            name='correo',
            field=models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator(message='Introduzca una dirección de correo electrónico válida'), django.core.validators.RegexValidator(code='invalid_correo', message='El correo debe tener al menos 5 caracteres después del "@" y terminar en ".cl" o ".com"', regex='^[^@]+@.{5,}(\\.cl|\\.com)$')]),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='mensaje_contacto',
            field=models.CharField(max_length=300, validators=[django.core.validators.MinLengthValidator(10, message='El mensaje debe tener al menos 10 caracteres'), django.core.validators.RegexValidator(code='invalid_mensaje_contacto', message='El mensaje solo puede contener letras y puntos. Además, no pueden ser solo puntos.', regex='^(?!.*([^a-zA-Z. ñÑáéíóúÁÉÍÓÚ])).*$'), contactos.models.validate_unique_chars, contactos.models.validate_message_sense]),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='nombre',
            field=models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(3, message='El nombre debe tener al menos 3 caracteres'), django.core.validators.RegexValidator(code='invalid_nombre', message='El nombre solo puede contener letras', regex='^[a-zA-ZñÑ]+$'), contactos.models.validate_unique_chars]),
        ),
    ]
