# Generated by Django 4.2.11 on 2024-04-30 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactos', '0010_rename_estado_contacto_contacto_id_estado_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contacto',
            old_name='id_estado',
            new_name='estado_contacto',
        ),
        migrations.RenameField(
            model_name='contacto',
            old_name='id_tipo',
            new_name='tipo_contacto',
        ),
        migrations.RemoveField(
            model_name='estado_contacto',
            name='id',
        ),
        migrations.RemoveField(
            model_name='tipo_contacto',
            name='id',
        ),
        migrations.AlterField(
            model_name='estado_contacto',
            name='estado_contacto',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tipo_contacto',
            name='tipo_contacto',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
