# Generated by Django 4.2.11 on 2024-05-02 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingrediente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_ingrediente', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_menu', models.CharField(max_length=50)),
                ('precio', models.PositiveIntegerField()),
                ('ganancia', models.PositiveIntegerField()),
                ('estado_menu', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Ingrediente_menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_ingrediente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='menus.ingrediente')),
                ('id_menu', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='menus.menu')),
            ],
        ),
    ]
