# Generated by Django 4.2.11 on 2024-05-03 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='imagen',
            field=models.ImageField(default=1, upload_to='images/'),
            preserve_default=False,
        ),
    ]
