# Generated by Django 4.2.11 on 2024-05-14 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0002_menu_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='descripcion_menu',
            field=models.CharField(default=123, max_length=300),
            preserve_default=False,
        ),
    ]
