# Generated by Django 4.2.11 on 2024-05-24 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0003_menu_descripcion_menu'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calificacion', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='menu',
            name='calificacion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='menus.calificacion'),
        ),
    ]
