# Generated by Django 4.2.11 on 2024-06-06 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0005_remove_menu_calificacion_calificacion_menu'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proteina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Salsa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_salsa', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Vegetal1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Vegetal2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Vegetal3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Vegetal4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Vegetal5',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='menu',
            name='proteina',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='menus.proteina'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='menu',
            name='salsa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='menus.salsa'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='menu',
            name='vegetal1',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='menus.vegetal1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='menu',
            name='vegetal2',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='menus.vegetal2'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='menu',
            name='vegetal3',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='menus.vegetal3'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='menu',
            name='vegetal4',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='menus.vegetal4'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='menu',
            name='vegetal5',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='menus.vegetal5'),
            preserve_default=False,
        ),
    ]
