# Generated by Django 4.2.11 on 2024-06-06 20:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0006_proteina_salsa_vegetal1_vegetal2_vegetal3_vegetal4_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vegetal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='vegetal1',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='vegetal2',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='vegetal3',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='vegetal4',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='vegetal5',
            name='nombre',
        ),
        migrations.AddField(
            model_name='vegetal1',
            name='vegetal_base',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='vegetal1', to='menus.vegetal'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vegetal2',
            name='vegetal_base',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='vegetal2', to='menus.vegetal'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vegetal3',
            name='vegetal_base',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='vegetal3', to='menus.vegetal'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vegetal4',
            name='vegetal_base',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='vegetal4', to='menus.vegetal'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vegetal5',
            name='vegetal_base',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='vegetal5', to='menus.vegetal'),
            preserve_default=False,
        ),
    ]
