# Generated by Django 4.2.11 on 2024-06-06 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0007_vegetal_remove_vegetal1_nombre_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salsa',
            old_name='nombre_salsa',
            new_name='nombre',
        ),
    ]
