# Generated by Django 4.2.11 on 2024-06-07 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0010_remove_menu_proteina_remove_menu_salsa_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vegetal1',
            name='vegetal_base',
        ),
        migrations.RemoveField(
            model_name='vegetal2',
            name='vegetal_base',
        ),
        migrations.RemoveField(
            model_name='vegetal3',
            name='vegetal_base',
        ),
        migrations.RemoveField(
            model_name='vegetal4',
            name='vegetal_base',
        ),
        migrations.RemoveField(
            model_name='vegetal5',
            name='vegetal_base',
        ),
        migrations.AddField(
            model_name='menu',
            name='proteina',
            field=models.ManyToManyField(to='menus.proteina'),
        ),
        migrations.AddField(
            model_name='menu',
            name='salsa',
            field=models.ManyToManyField(to='menus.salsa'),
        ),
        migrations.AddField(
            model_name='menu',
            name='vegetal',
            field=models.ManyToManyField(to='menus.vegetal'),
        ),
        migrations.DeleteModel(
            name='Ingrediente_menu',
        ),
        migrations.DeleteModel(
            name='Vegetal1',
        ),
        migrations.DeleteModel(
            name='Vegetal2',
        ),
        migrations.DeleteModel(
            name='Vegetal3',
        ),
        migrations.DeleteModel(
            name='Vegetal4',
        ),
        migrations.DeleteModel(
            name='Vegetal5',
        ),
    ]
