# Generated by Django 4.2.11 on 2024-06-14 22:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0011_remove_vegetal1_vegetal_base_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='descripcion_menu',
            field=models.CharField(max_length=300, validators=[django.core.validators.MinLengthValidator(10)]),
        ),
        migrations.AlterField(
            model_name='menu',
            name='ganancia',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='menu',
            name='nombre_menu',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(code='invalid_nombre_menu', message='El nombre del menú solo puede contener letras.', regex='^[a-zA-Z]+$')]),
        ),
        migrations.AlterField(
            model_name='menu',
            name='precio',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
