# Generated by Django 4.2.11 on 2024-06-19 23:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0021_alter_proteina_nombre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(3), django.core.validators.RegexValidator(message='El nombre de la categoria solo puede contener letras y debe ser mayor a 3 letras', regex='^[a-zA-Z ]+$')])),
            ],
        ),
    ]
