# Generated by Django 4.2.11 on 2024-06-19 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0022_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='categoria',
            field=models.ManyToManyField(to='menus.categoria'),
        ),
    ]
