# Generated by Django 4.2.11 on 2024-06-22 04:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0026_alter_menu_nombre_menu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='nombre',
            field=models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(3), django.core.validators.RegexValidator(message='El nombre de la categoria solo puede contener letras y debe ser mayor a 3 letras', regex='^[a-zA-ZñÑ ]+$')]),
        ),
        migrations.AlterField(
            model_name='menu',
            name='descripcion_menu',
            field=models.CharField(max_length=300, validators=[django.core.validators.MinLengthValidator(10), django.core.validators.RegexValidator(code='invalid_descripcion_menu', message='La descripción solo puede contener letras, números, puntos y espacios. No puede estar compuesta solo por puntos o espacios.', regex='^(?!^[.\\s]*$)[a-zA-Z0-9áéíóúñÑÁÉÍÓÚ.,\\s]+$')]),
        ),
        migrations.AlterField(
            model_name='menu',
            name='nombre_menu',
            field=models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(8), django.core.validators.RegexValidator(code='invalid_nombre_menu', message='El nombre del menú debe comenzar con una letra mayúscula y solo puede contener letras y espacios.', regex='^[A-ZÑ][a-zA-ZñÑ ]+$')]),
        ),
        migrations.AlterField(
            model_name='proteina',
            name='nombre',
            field=models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(3), django.core.validators.RegexValidator(message='El nombre de la proteina solo puede contener letras y debe ser mayor a 3 letras', regex='^[a-zA-ZñÑ ]+$')]),
        ),
        migrations.AlterField(
            model_name='salsa',
            name='nombre',
            field=models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(3), django.core.validators.RegexValidator(message='El nombre de la salsa solo puede contener letras y debe ser mayor a 3 letras', regex='^[a-zA-ZñÑ ]+$')]),
        ),
        migrations.AlterField(
            model_name='vegetal',
            name='nombre',
            field=models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(3), django.core.validators.RegexValidator(message='El nombre del vegetal solo puede contener letras y debe ser mayor a 3 letras', regex='^[a-zA-ZñÑ ]+$')]),
        ),
    ]
